web-a:
    build: ./web
    expose:
        - 80
    tty: true
    stdin_open: true

web-b:
    build: ./web
    expose:
        - 80
    tty: true
    stdin_open: true

web-c:
    build: ./web
    expose:
        - 80
    tty: true
    stdin_open: true

web-d:
    build: ./web
    expose:
        - 80
    tty: true
    stdin_open: true

proxy:
    build: ./proxy
    links:
        - web-a
        - web-b
        - web-c
        - web-d
    ports:
        - "80:80"
        - "22"
    expose:
        - "80"
        - "22"
    tty: true
    stdin_open: true
